modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPLv3"

[[mods]]
modId="vtweaks"
version="${file.jarVersion}"
displayName="V-Tweaks"
displayURL="http://github.com/oitsjustjose/v-tweaks"
credits=""
authors="oitsjustjose"
description='''A mod that tweaks the vanilla game without adding any new items'''

[[dependencies.vtweaks]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vtweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
