modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="http://github.com/oitsjustjose/v-tweaks/issues"
[[mods]]
modId="vtweaks"
version="${version}"
displayName="V-Tweaks"
displayURL="http://github.com/oitsjustjose/v-tweaks"
credits=""
authors="oitsjustjose"
description='''
A mod that tweaks the vanilla game without adding any new items
'''
[[dependencies.vtweaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.vtweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
